name = "sm-auth-survey-api"
main = "src/index.js"
compatibility_date = "2024-09-05"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "sm-auth-survey-api"

[env.staging]
name = "sm-auth-survey-api-staging"

[env.development]
name = "sm-auth-survey-api-dev"

# D1 数据库配置（CI 会自动填充 ID）
[[d1_databases]]
binding = "DB"
database_name = "sm-auth-survey-db"
database_id = "PLACEHOLDER_D1_ID"

# R2 存储配置
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "sm-auth-survey-files"

# KV 存储配置（CI 会自动填充 ID）
[[kv_namespaces]]
binding = "CACHE"
id = "PLACEHOLDER_KV_ID"
preview_id = "PLACEHOLDER_KV_ID"

# 环境变量
[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"
